package com.example.pedometer.util

const val DEFAULT_GOAL = 10000
const val SIZE_GOAL_LINE = 24f
const val SIZE_GOAL_LINE_WIDTH = 8f
const val SIZE_AVERAGE_LINE_WIDTH = 5f
const val SIZE_SPACE = 0.5f
const val TEXT_SIZE_X_AXIS = 12f
const val EXTRA_BOTTOM_OFFSET = 12f
const val SIZE_X_RANGE_MAXIMUM = 6f
const val SIZE_BAR_WIDTH = 0.25f
const val TEXT_SIZE_AVERAGE_LINE = 24f
const val SIZE_RADIUS = 20

const val DURATION_ANIMATION_Y = 1000
const val TEXT_SIZE_PIE_CHART_CENTER_TITLE_TEXT = 6f
const val TEXT_SIZE_PIE_CHART_CENTER_SUB_TEXT = 3f
const val PIE_DATA_SET_SLICE_SPACE = 2f
const val TEXT_SIZE_PIE_DATA_SET_VALUE = 12f
const val HOLE_RADIUS_PIE_CHART = 80f
const val TRANSPARENT_CIRCLE_RADIUS_PIE_CHART = 79f
const val LINE_LENGTH_DASHED_LINE = 25f
const val SPACE_LENGTH_DASHED_LINE = 10f
const val REQUEST_CODE_STEP_COUNT = 999
const val MICROSECONDS_IN_ONE_MINUTE: Long = 60000000
const val PEDOMETER_NOTIFICATION_ID = 1
const val PEDOMETER_NOTIFICATION_CHANNEL_ID = "Pedometer Notification"
const val TEXT_PEDOMETER = "pedometer"
const val FLAG_HOME = 0
const val FLAG_HISTORY = 1
const val FLAG_SETTING = 2

